### ISSUE TITLE
Issues with margin and padding

### ISSUE THREAD

**Issue by meaningfool** [hrescak/Sketch-Flex-Layout#11]
Hey Matej, great work, this is showing a lot of promise, especially for people like me that are toying with design tools on the side. 

However I have been wrestling with bugs relative to positioning. I tried all I could for the past few hours, but there are things that won't come around. So I tried to come up with qualified bugs not to loose what I've gathered. In the file, if you just select the .container at the bottom of the iPhone Artboard, and "Add object from prototype", you can see the following issues :
1. The text layer "Des scientifiques ont prouvé..." was applied 
- The padding from the outer .row group (12 px on the left = 6 + 6, with .row -> paddingLeft = 6)
- Twice the marginBottom (= 5 px) from the previous element .source (hence there is a 17 px gap between the bottom of .source and the text element, which corresponds to 2*5 + 7 where 7 px is the paddingBottom from the outer .row group, cf preceding remark
  1. Strangely the 1st issue disappears when I hit Cmd+Ctrl+L. However it does not solve the same problem for the .separator group which remains offset

https://drive.google.com/file/d/0B0lA1rMVev-cZWxJZEtiUDFtR2s/view?usp=sharing

Hope this helps. I'm eager to see it working properly !
Cheers,
Josselin

**Comment by meaningfool** [comment]
Trying to find a way around, I defaulted on the stylesheet solution. And I think the issue might not be with the prototypes but with the interpretation of the resulting stylesheet in my previous comment. 

In this second file I could identify that the layout properties and the values are misused like if there was a problem of context, or a problem of indexing in an array : 
- For the first CSS block, paddingTop (9px) and paddingLeft (8px) are correctly applied
- At the second block the paddingRight takes the value of paddingTop (9px instead of 7)
- At the 3rd block the marginBottom takes the value of the first block's paddingLeft (8px instead of 4)
- At the 4th block the marginTop takes the value of 6 px instead of 3px, wich could be the 2nd block's borderBottomWidth (this property was ignored as for the border-width)
- The 5th block is positioned relatively to the 3rd block I guess and not relatively to the 4th. And its "margin" to the 3rd block is 9 px (= the first block paddingTop)
- Its padding to the bottom is 8px (the first block paddingLeft)

It feels an array is being fed with new values as we go through the CSS these values being popped to create the layout, and the starting all over from the first value in the stack when it has been emptied... It might be just some random observations that I'm trying to make sense of, but if that can help...

Josselin

https://drive.google.com/file/d/0B0lA1rMVev-cV19uemJnMXFFSkU/view?usp=sharing

**Comment by hrescak** [comment]
Hi Josselin! The problem with styles being applied twice was because both your group and the containing layer had the same class name (.title group with .title text layer) so they're both being matched and styles applied to them. Here's the fixed prototype file: https://www.dropbox.com/s/oq73k3pvr3rn7cx/Instapaper.sketch?dl=0
