### ISSUE TITLE
relative to parent values

### ISSUE THREAD

**Issue by ademilter** [hrescak/Sketch-Flex-Layout#13]
Do you think of adding relative percentage value support in the future?

**Comment by jasonkylefrank** [comment]
I agree with @ademilter - **percentage** width & height would be a huge step forward for this plugin!  Percentage of parent width/height and percentage of the artboard width/height would both be great.

**Comment by hrescak** [comment]
The css layout library I'm using for this currently doesn't support percentage values, but you can simulate it by using the flex property. If you place two elements next to eachother and one of them has flex:1 and the other one flex:2, they will be positioned at 33% and 66% width

**Comment by jasonkylefrank** [comment]
@hrescak Good point about using the flex-grow property to emulate percentages.  I've been able to use that to get an object to stretch to 100% width of its parent if that parent object has a width number set.  But what would be really nice is if I could get something to stretch to 100% width of an _artboard_.  The only way I could get that to work was by setting a width of the top-level prototype object to be the same width as the artboard.  Then the next child down could use `flex:1`.  See this screenshot:

![image](https://cloud.githubusercontent.com/assets/7502365/10265567/5be9ade0-6a03-11e5-8caf-1b5c1ebd438a.png)

Thanks for the great plugin @hrescak!

**Comment by ademilter** [comment]
@hrescak :+1:  @jasonkylefrank :100:
