### ISSUE TITLE
Sketch Version 3.5.2 (25235) not supported?

### ISSUE THREAD

**Issue by twotolab** [hrescak/Sketch-Flex-Layout#17]
Hello,
I just wanted to know if someone else is having similar problems?!
If yes.How can I support to fix the bug?
regards,
Patrick

**Comment by rabbit-roger** [comment]
I have the same problem.

**Comment by pixelatorz** [comment]
same here in 3.6.1 doesn't seem to work anymore

**Comment by laureld** [comment]
I have most of the functionality in 3.6.1, but once I start making more complex rules everything breaks.

**Comment by sebastienbarre** [comment]
Same here, behaving weirdly.
