### ISSUE TITLE
Sketch 39.1

### ISSUE THREAD

**Issue by cinpossible** [hrescak/Sketch-Flex-Layout#21]
Hey, is it still supporting on Sketch 39.1 cos I was pressing Ctl Cmd L and it did not work. (every previous steps I did were absolutely right)

**Comment by zilos** [comment]
Hello, I think this will tremendously help our team for our designs and components, but the plugin is not working for v 39.1. Will there be a fix for it? 

thanks for the hard work.

B

**Comment by rodnem** [comment]
same here
