### ISSUE TITLE
Need a way to assign classes to layers (in bulk)

### ISSUE THREAD

**Issue by eertmann** [hrescak/Sketch-Flex-Layout#3]
Would be nice to have a method for assigning classes to layers, other than manually editing and typing on each layer. Maybe a plugin which allows me to append a string to the end of layer names, ideally if it were smart enough to recognize class names that had already been assigned and let me just select from that list.

**Comment by hrescak** [comment]
This is now possible with my [other plugin](https://github.com/hrescak/Sketch-Layer-Name-Tools)
