### ISSUE TITLE
Unclear you have to exit the selection state to run the plugin

### ISSUE THREAD

**Issue by nlevin** [hrescak/Sketch-Flex-Layout#6]
Currently the plugin fails silently if you try to run it without saving your sketch file. Lots of options to fix this, for example:
1. Save the file automatically when you run the plugin
2. Don't require saving to run the plugin
3. Let users know in the readme you need to save it to work

**Comment by hrescak** [comment]
I'm trying to repro this, what version of the app are you using? is it via app store / direct download? Can you also attach the file please? I haven't experienced this.

**Comment by nlevin** [comment]
Running Sketch Beta Version 3.3.2 (12041) direct download using your sample file from the repo.

EDIT: Ok I think I figured it out. Sorry, turns out it wasn't to do with saving, it was about the selection state. While my cursor was still editing the stylesheet I can't build, I have to hit esc first. Makes sense, but tripped me up at first.

**Comment by nlevin** [comment]
Screen recording: http://nlev.in/btKd

**Comment by hrescak** [comment]
My bad, I'll update the readme to reflect this.
